
from variant import (CHROM_FIELD, POS_FIELD, ID_FIELD, REF_FIELD, ALT_FIELD, 
                     QUAL_FIELD, GT_FIELD, GQ_FIELD, DP_FIELD, AO_FIELD,
                     RO_FIELD, AD_FIELD, SAMPLE_FIELD)

SCIKIT_ALLEL_VARIANTS_GROUP_NAME = 'variants'
SCIKIT_ALLEL_CALL_GROUP_NAME = 'calldata'

SCIKIT_ALLEL_CHROM_FIELD_NAME = 'CHROM'
SCIKIT_ALLEL_POS_FIELD_NAME = 'POS'
SCIKIT_ALLEL_ID_FIELD_NAME = 'ID'
SCIKIT_ALLEL_REF_FIELD_NAME = 'REF'
SCIKIT_ALLEL_ALT_FIELD_NAME = 'ALT'
SCIKIT_ALLEL_QUAL_FIELD_NAME = 'QUAL'
SCIKIT_ALLEL_GT_FIELD_NAME = 'GT'
SCIKIT_ALLEL_GQ_FIELD_NAME = 'GQ'
SCIKIT_ALLEL_DP_FIELD_NAME = 'DP'
SCIKIT_ALLEL_AO_FIELD_NAME = 'AO'
SCIKIT_ALLEL_RO_FIELD_NAME = 'RO'
SCIKIT_ALLEL_AD_FIELD_NAME = 'AD'

SCIKIT_ALLEL_FIELD_DEFINITIONS = {
    CHROM_FIELD: {'group': SCIKIT_ALLEL_VARIANTS_GROUP_NAME, 'field': SCIKIT_ALLEL_CHROM_FIELD_NAME},
    POS_FIELD: {'group': SCIKIT_ALLEL_VARIANTS_GROUP_NAME, 'field': SCIKIT_ALLEL_POS_FIELD_NAME},
    ID_FIELD: {'group': SCIKIT_ALLEL_VARIANTS_GROUP_NAME, 'field': SCIKIT_ALLEL_ID_FIELD_NAME},
    REF_FIELD: {'group': SCIKIT_ALLEL_VARIANTS_GROUP_NAME, 'field': SCIKIT_ALLEL_REF_FIELD_NAME},
    ALT_FIELD: {'group': SCIKIT_ALLEL_VARIANTS_GROUP_NAME, 'field': SCIKIT_ALLEL_ALT_FIELD_NAME},
    QUAL_FIELD: {'group': SCIKIT_ALLEL_VARIANTS_GROUP_NAME, 'field': SCIKIT_ALLEL_QUAL_FIELD_NAME},
    GT_FIELD: {'group': SCIKIT_ALLEL_CALL_GROUP_NAME, 'field': SCIKIT_ALLEL_GT_FIELD_NAME},
    GQ_FIELD: {'group': SCIKIT_ALLEL_CALL_GROUP_NAME, 'field': SCIKIT_ALLEL_GQ_FIELD_NAME},
    DP_FIELD: {'group': SCIKIT_ALLEL_CALL_GROUP_NAME, 'field': SCIKIT_ALLEL_DP_FIELD_NAME},
    AO_FIELD: {'group': SCIKIT_ALLEL_CALL_GROUP_NAME, 'field': SCIKIT_ALLEL_AO_FIELD_NAME},
    RO_FIELD: {'group': SCIKIT_ALLEL_CALL_GROUP_NAME, 'field': SCIKIT_ALLEL_RO_FIELD_NAME},
    AD_FIELD: {'group': SCIKIT_ALLEL_CALL_GROUP_NAME, 'field': SCIKIT_ALLEL_AD_FIELD_NAME}
}

SCIKIT_ALLEL_FIELD_PATHS = {
    key: f'{value["group"]}/{value["field"]}' for key, value in SCIKIT_ALLEL_FIELD_DEFINITIONS.items()}

SCIKIT_ALLEL_FIELD_PATHS[SAMPLE_FIELD] = 'samples'

FIELDS_FROM_SCIKIT_ALLEL_FIELD_PATHS = {value: key for key, value in SCIKIT_ALLEL_FIELD_PATHS.items()}
